/*
  This file will be overwritten by wxDev-C++ at every compile.
  Do not edit this file as your changes will be lost.
  You can, however, include this file and use the defines.
*/
#ifndef SDL_PRIVATE_H
#define SDL_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.1.1"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	1
#define COMPANY_NAME	"VAPZ"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"VAPZ OpenGL test"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"com.vapz.app"
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*SDL_PRIVATE_H*/
